# Generated by Django 6.0.7 on 2026-07-31 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_maingoal_priority_alter_maingoal_title_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='chore',
            name='milestone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chores', to='api.milestone'),
        ),
        migrations.CreateModel(
            name='DayRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.IntegerField(default=0)),
                ('sleep', models.IntegerField(default=0)),
                ('rest', models.IntegerField(default=0)),
                ('day', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
