# Generated by Django 6.0.7 on 2026-08-01 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_chore_milestone_dayrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milestone',
            name='progress',
        ),
    ]
